_version: 31
anticheat:
  anti-xray:
    enabled: true
    engine-mode: 2
    hidden-blocks:
      - ancient_debris
      - nether_gold_ore
      - nether_quartz_ore
    lava-obscures: false
    max-block-height: 128
    replacement-blocks:
      - basalt
      - blackstone
      - gravel
      - netherrack
      - soul_sand
      - soul_soil
    update-radius: 2
    use-permission: false
